name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write

    if: ${{ github.repository_owner == 'cloudflare' }}
    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --child-concurrency=10

      - name: Test and Build
        run: pnpm nx build workers-ai-provider

      - id: changesets
        uses: changesets/action@v1
        with:
          version: ./.github/version-and-install.sh
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.CLOUDFLARE_AI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
